plugins { id 'com.android.application' }
android {
  namespace 'com.friendshipglobaldesign.hunter'
  compileSdk 35
  defaultConfig {
    applicationId "com.friendshipglobaldesign.hunter"
    minSdk 26
    targetSdk 34
    versionCode 21
    versionName "0.6.1"
  }
  buildTypes {
    release { minifyEnabled false }
    debug { minifyEnabled false }
  }
}