plugins { id 'com.android.application' }

android {
  namespace 'com.friendshipglobaldesign.hunter'
  compileSdk 35

  defaultConfig {
    applicationId "com.friendshipglobaldesign.hunter"
    minSdk 26
    targetSdk 34
    versionCode 7
    versionName "0.4.2"
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }
}